### ISSUE TITLE
update readme for stripping out unused scenarios

### ISSUE THREAD

**Issue by dave99galloway** [AndyLPK247/SpecFlowPlusLivingDocScripts#2]
Fleshed out the readme for stripping out unused scenarios a bit as I had a bit of trouble following them

**Comment by dave99galloway** [comment]
fixed in https://github.com/AndyLPK247/SpecFlowPlusLivingDocScripts/pull/1

**Comment by AutomationPanda** [comment]
Thanks for the suggestion. I'll review shortly.

**Comment by AndyLPK247** [comment]
I updated the README.
