### ISSUE TITLE
[BUG] Resulting pruned FeatureData truncated due to max JSON depth set to 20

### ISSUE THREAD

**Issue by fkurzyk** [AndyLPK247/SpecFlowPlusLivingDocScripts#4]
I have run into an issue using the `RemoveSkippedScenarios.ps1` script when resulting pruned FeatureData has been truncated in depth due to max JSON depth set to 20 in the script:

```
❯ .\RemoveSkippedScenarios.ps1 .\TestExecution_combined.json .\FeatureData.json .\FeatureData_pruned.json
Reading '.\FeatureData.json'
Reading '.\TestExecution_combined.json'
Hashing each Test Execution scenario from '.\TestExecution_combined.json'
106 Test Execution scenario(s) found
Pruning unexecuted scenarios from Feature Data
Saving the pruned Feature Data to '.\FeatureData_pruned.json'
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 20.
```

This happened in a project with feature files living in a deep directory structure, which seems to be the reason for maxing-out the JSON depth (`"Folders"` under `"Folders"` under `"Folders"` etc.)

As a result some data in the resulting `FeatureData.json` was not serialized correctly, eg.
```
"TableRows": [
  "@{Cells=System.Object[]}",
  "@{Cells=System.Object[]}",
  "@{Cells=System.Object[]}",
  "@{Cells=System.Object[]}"
```

**Comment by fkurzyk** [comment]
Proposed trivial fix in PR #5

**Comment by fkurzyk** [comment]
@AutomationPanda pinging you here as I am not sure if you receive notifications on the @AndyLPK247 account

**Comment by AutomationPanda** [comment]
Thanks for the pull request! I approved and merged it.
